# Generated by Django 4.2.4 on 2023-09-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_amount_spent_expensesbase_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesbase',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
