# Generated by Django 4.2.4 on 2023-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expense_expensecategory_remove_expensesbase_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='short_name',
            field=models.CharField(default='entertainment', max_length=255),
            preserve_default=False,
        ),
    ]
