# Generated by Django 4.2.4 on 2023-09-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticketreply',
            name='status',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default='Open', max_length=255),
            preserve_default=False,
        ),
    ]
