# Generated by Django 4.2.4 on 2023-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_supportticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='body',
            field=models.TextField(verbose_name='Ticket Body'),
        ),
    ]
