# Generated by Django 4.2.4 on 2024-01-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_expense_amount_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='supportticketreply',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='SupportTicketReply',
        ),
    ]
