# Generated by Django 4.2.4 on 2023-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_expensesbase_entertainmentexpenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesbase',
            name='amount',
        ),
        migrations.AddField(
            model_name='expensesbase',
            name='amount_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expensesbase',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
