# Generated by Django 4.2.4 on 2023-09-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_expensesbase_amount_expensesbase_amount_spent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensesbase',
            old_name='amount_spent',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='expensesbase',
            name='budget',
        ),
        migrations.AddField(
            model_name='expensesbase',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
