# Generated by Django 4.2.4 on 2023-09-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_expensecategory_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='short_name',
        ),
    ]
