# Generated by Django 4.2.4 on 2023-09-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_supportticketreply_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Staff Replied', 'Staff Replied'), ('User Replied', 'User Replied'), ('Closed', 'Closed')], default='Open', max_length=255),
        ),
    ]
