# Generated by Django 4.2.4 on 2023-09-16 06:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_supportticket_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='hex_color',
            field=models.CharField(max_length=255, verbose_name='Hex Color'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='long_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='supportticketreply',
            name='body',
            field=models.TextField(verbose_name='Ticket Body'),
        ),
        migrations.AlterField(
            model_name='supportticketreply',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
